# Generated by Django 5.1 on 2024-08-31 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_client_alter_skills_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='link',
            field=models.URLField(default='null', verbose_name='LINK'),
        ),
    ]
