# Generated by Django 5.1 on 2024-09-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_client_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('subject', models.CharField(max_length=150, verbose_name='Titulo')),
                ('email', models.CharField(max_length=150, verbose_name='Correo')),
                ('photo', models.ImageField(default='image.png', upload_to='', verbose_name='Foto')),
                ('messege', models.TextField(verbose_name='Mensaje')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Creacion')),
                ('updated', models.DateField(auto_now=True, verbose_name='Actualizacion')),
            ],
            options={
                'verbose_name': 'Reseña',
                'verbose_name_plural': 'Reseñas',
            },
        ),
    ]
