# Generated by Django 5.1 on 2024-09-10 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='photo',
            field=models.ImageField(default='imagen.png', upload_to='Reviews', verbose_name='Foto'),
        ),
    ]
