# Generated by Django 5.1 on 2024-09-11 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Editado el')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nombre')),
                ('icon', models.CharField(max_length=100, verbose_name='icono')),
                ('image', models.ImageField(default='null', upload_to='tours')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Editado el')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Portafolio',
                'verbose_name_plural': 'Portafolio',
            },
        ),
    ]
