# Generated by Django 5.1 on 2024-09-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titulo')),
                ('verificate', models.CharField(max_length=150, verbose_name='Titulo')),
                ('data_certi', models.DateField(verbose_name='Fecha de certificado')),
                ('logo', models.ImageField(upload_to='certificate', verbose_name='Logo')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Creacion')),
                ('updated', models.DateField(auto_now=True, verbose_name='Actualizacion')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
            },
        ),
    ]
