# Generated by Django 5.1 on 2024-09-11 20:47

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_skillscode_skillsdesing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('year', models.IntegerField(verbose_name='Año')),
                ('company', models.CharField(max_length=150, verbose_name='Compañia')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Creacion')),
                ('updated', models.DateField(auto_now=True, verbose_name='Actualizacion')),
            ],
            options={
                'verbose_name': 'Experiencia',
                'verbose_name_plural': 'Experiencias',
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('year', models.IntegerField(verbose_name='Año')),
                ('company', models.CharField(max_length=150, verbose_name='Compañia')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Creacion')),
                ('updated', models.DateField(auto_now=True, verbose_name='Actualizacion')),
            ],
            options={
                'verbose_name': 'Formacion',
                'verbose_name_plural': 'Formaciones',
            },
        ),
        migrations.AlterField(
            model_name='skillscode',
            name='percentage',
            field=models.IntegerField(verbose_name='Porcentaje'),
        ),
        migrations.AlterField(
            model_name='skillsdesing',
            name='percentage',
            field=models.IntegerField(verbose_name='Porcentaje'),
        ),
    ]
