# Generated by Django 5.1 on 2024-09-11 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_experience_training_alter_skillscode_percentage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='training',
            options={'ordering': ['year'], 'verbose_name': 'Formacion', 'verbose_name_plural': 'Formaciones'},
        ),
        migrations.AlterField(
            model_name='experience',
            name='year',
            field=models.CharField(max_length=100, verbose_name='Año'),
        ),
    ]
